### ISSUE TITLE
500: Internal Server Error

### ISSUE THREAD

**Issue by quantum77** [petegallagher/plugin.video.zoneminder#11]
Fedora 35 in a KVM VM, Kodi 19.3-1, plugin v3.0.0 .

ZM is listening on 127.0.0.1:1380 with no auth.  Set the plugin URL to http://127.0.0.1:1380, zm path zm, CGI path cgi-bin-zm...

However under API version my only choices are 'Music' or 'Pictures'?  Huh?

Auth enabled is Off, but my only choices under Frames per second (max) are 'October', {blank}, 'Pictures', 'Music', 'Settings', {blank}, 'Friday', {blank}, or 'May'.

2022-02-06 10:38:03.181 T:14311   ERROR <general>: EXCEPTION Thrown (PythonToCppException) : -->Python callback/script returned the following error<--
                                                    - NOTE: IGNORING THIS CAN LEAD TO MEMORY LEAKS!
                                                   Error Type: <class 'json.decoder.JSONDecodeError'>
                                                   Error Contents: Expecting value: line 1 column 1 (char 0)
                                                   Traceback (most recent call last):
                                                     File "/home/bill/.kodi/addons/plugin.video.zoneminder/zoneminder.py", line 212, in <module>
                                                       router(sys.argv[2][1:])
                                                     File "/home/bill/.kodi/addons/plugin.video.zoneminder/zoneminder.py", line 184, in router
                                                       _auth_token, _auth_token_param = login()
                                                     File "/home/bill/.kodi/addons/plugin.video.zoneminder/zoneminder.py", line 76, in login
                                                       j = json.loads(r.text)
                                                     File "/usr/lib64/python3.10/json/__init__.py", line 346, in loads
                                                       return _default_decoder.decode(s)
                                                     File "/usr/lib64/python3.10/json/decoder.py", line 337, in decode
                                                       obj, end = self.raw_decode(s, idx=_w(s, 0).end())
                                                     File "/usr/lib64/python3.10/json/decoder.py", line 355, in raw_decode
                                                       raise JSONDecodeError("Expecting value", s, err.value) from None
                                                   json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)
                                                   -->End of Python script error report<--

2022-02-06 10:38:03.207 T:14311    INFO <general>: Python interpreter stopped
2022-02-06 10:38:03.210 T:14310   ERROR <general>: GetDirectory - Error getting plugin://plugin.video.zoneminder/
2022-02-06 10:38:03.214 T:14263   ERROR <general>: CGUIMediaWindow::GetDirectory(plugin://plugin.video.zoneminder/) failed

**Comment by fabriziopicconi** [comment]
label should be fixed with today commit
